version: '3.7'

services:
  punctuation-service:
    image: linto-punctuation:latest
    volumes:
      - /path/to/your/model.mar/usr/src/app/model-store/model
    env_file: .env
    deploy:
      replicas: 1
    networks:
      - your-net

networks:
  your-net:
    external: true
