swagger: "2.0"

info:
  version: "1.0.0"
  title: LinTo-Platform-Punctuation
  description: Punctuation API
  contact:
    email: "support@linto.ai"
  license:
    name: "AGPLv3"
    url: "https://www.gnu.org/licenses/agpl-3.0.en.html"

schemes:
  - http
basePath: /

paths:
  /punctuation:
    post:
      tags:
        - "Punctuation API"
      summary: Perform punctuation
      consumes:
      - "application/json"
      - "text/plain"
      produces:
      parameters:
        - name: "sentences"
          in: body
          description: "Sentences to be punctuated"
          schema:
            type: object
            required: 
              - sentences
            properties:
              sentences:
                type: array
                items:
                  type: string
      responses:
        200:
          description: Successfully added punctuation
        400:
          description: Request error
        500:
          description: Server error

  /healthcheck:
    get:
      tags:
        - "Health"
      summary: Check server health
      consumes:
      - "application/json"
      responses:
        200:
          description: Healthcheck passes
        400:
          description: Healthcheck fails
        500:
          description: Healthcheck fails